name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Lint
        run: ./gradlew lintDebug
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: app/build/reports/lint-results-lintDebug.html
          if-no-files-found: ignore





